services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    labels:
      - "snadboy.revp.8181.domain=tautulli.isnadboy.com"
      - "docktail.service.enable=true"
      - "docktail.service.name=tautulli"
      - "docktail.service.port=8181"
      - "docktail.service.service-port=443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - tautulli-data:/config
    ports:
      - 8181:8181
    restart: unless-stopped

volumes:
  tautulli-data:
    external: true
