#!/bin/sh

declare thread_if
declare otbr_forward_ingress_chain
declare otbr_forward_egress_chain

thread_if="${OTBR_THREAD_IF:-wpan0}"
otbr_forward_ingress_chain="OTBR_FORWARD_INGRESS"
otbr_forward_egress_chain="OTBR_FORWARD_EGRESS"
