services:
  overseerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: overseerr
    ports:
      - 5055:5055
    volumes:
      - overseerr-data:/app/config
    labels:
      - "snadboy.revp.5055.domain=overseerr.isnadboy.com"
      - "docktail.service.enable=true"
      - "docktail.service.name=overseerr"
      - "docktail.service.port=5055"
      - "docktail.service.service-port=443"
    environment:
      - TZ=America/Chicago
    restart: unless-stopped

volumes:
  overseerr-data:
    external: true
