services:
  overseerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: overseerr
    labels:
      - "snadboy.revp.5055.domain=overseerr.isnadboy.com"
    environment:
      - TZ=America/Chicago
      - PORT=5055
    volumes:
      - overseerr-data:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

volumes:
  overseerr-data:
    external: true
