services:
  pwa-appserver:
    image: ghcr.io/snadboy/pwa:latest
    container_name: pwa-appserver
    restart: unless-stopped
    ports:
      - "8200:8200"
    volumes:
      - pwa-logs:/app/logs
    labels:
      - "snadboy.revp.8200.domain=calculator.isnadboy.com,inventory.isnadboy.com,plex-recent.isnadboy.com,pwa.isnadboy.com,tag-youre-it.isnadboy.com,cumulus-ledger.isnadboy.com,infra-test.isnadboy.com"

volumes:
  pwa-logs:
