services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    labels:
      - "snadboy.revp.8080.domain=sabnzbd.isnadboy.com"
      - "docktail.service.enable=true"
      - "docktail.service.name=sabnzbd"
      - "docktail.service.port=8080"
      - "docktail.service.service-port=443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - sabnzbd-config:/config
      - /mnt/docker/downloads:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  sabnzbd-config:
    external: true
