blueprint:
  name: Lights - Occupancy
  description: >
    Control lights based on an occupancy sensor. Choose to turn lights on when
    occupied, off when unoccupied, or both — with optional delays on each.
  domain: automation
  input:
    occupancy_sensor:
      name: Occupancy Sensor
      description: Binary sensor that detects occupancy or presence
      selector:
        entity:
          domain: binary_sensor

    light_entity:
      name: Light
      description: Light or light group to control
      selector:
        entity:
          domain: light

    mode:
      name: Control Mode
      description: >
        "Turn Off Only" turns lights off when unoccupied (default).
        "Turn On Only" turns lights on when occupied.
        "Both" turns lights on when occupied and off when unoccupied.
      default: lights_off_only
      selector:
        select:
          options:
            - value: lights_off_only
              label: "Turn Off Only (when unoccupied)"
            - value: lights_on_only
              label: "Turn On Only (when occupied)"
            - value: both
              label: "Both (on when occupied, off when unoccupied)"

    on_delay:
      name: Turn On Delay (seconds)
      description: >
        Seconds to wait after occupancy is detected before turning the light on.
        Used when mode is "Turn On Only" or "Both".
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
          mode: box

    off_delay:
      name: Turn Off Delay (seconds)
      description: >
        Seconds to wait after no occupancy before turning the light off.
        Used when mode is "Turn Off Only" or "Both".
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
          mode: box

    max_on_duration:
      name: Maximum On Duration (minutes)
      description: >
        Turns the light off after it has been on this many minutes, regardless
        of occupancy. Set to 0 to disable. Used when mode is "Turn Off Only"
        or "Both".
      default: 60
      selector:
        number:
          min: 0
          max: 480
          unit_of_measurement: min
          mode: box

variables:
  mode: !input mode
  max_on_duration: !input max_on_duration

trigger:
  - trigger: state
    entity_id: !input occupancy_sensor
    to: 'off'
    for:
      seconds: !input off_delay
    id: occupancy_off

  - trigger: state
    entity_id: !input occupancy_sensor
    to: 'on'
    for:
      seconds: !input on_delay
    id: occupancy_on

  - trigger: state
    entity_id: !input light_entity
    to: 'on'
    for:
      minutes: !input max_on_duration
    id: max_duration_exceeded

  - trigger: homeassistant
    event: start
    id: startup

  - trigger: event
    event_type: automation_reloaded
    id: reload

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - occupancy_off
              - startup
              - reload
          - condition: template
            value_template: "{{ mode in ['lights_off_only', 'both'] }}"
          - condition: state
            entity_id: !input light_entity
            state: 'on'
          - condition: state
            entity_id: !input occupancy_sensor
            state: 'off'
        sequence:
          - action: light.turn_off
            target:
              entity_id: !input light_entity

      - conditions:
          - condition: trigger
            id:
              - occupancy_on
          - condition: template
            value_template: "{{ mode in ['lights_on_only', 'both'] }}"
          - condition: state
            entity_id: !input occupancy_sensor
            state: 'on'
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input light_entity

      - conditions:
          - condition: trigger
            id:
              - max_duration_exceeded
          - condition: template
            value_template: "{{ mode in ['lights_off_only', 'both'] and max_on_duration | int > 0 }}"
          - condition: state
            entity_id: !input light_entity
            state: 'on'
        sequence:
          - action: light.turn_off
            target:
              entity_id: !input light_entity

mode: restart
