FROM python:3.12-alpine

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .

EXPOSE 8080
CMD ["gunicorn", "-w", "1", "--threads", "2", "-b", "0.0.0.0:8080", "--access-logfile", "-", "app:app"]
