services:
  pulse:
    image: rcourtman/pulse:latest
    container_name: pulse
    ports:
      - "7655:7655"
    volumes:
      - pulse_data:/data
    labels:
      - "snadboy.revp.7655.domain=pulse.isnadboy.com"
    environment:
      - TZ=America/Chicago
      - PULSE_PUBLIC_URL=https://pulse.isnadboy.com
      - PULSE_AGENT_CONNECT_URL=https://pulse.isnadboy.com
    restart: unless-stopped

volumes:
  pulse_data:
    external: true
