services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    labels:
      - "snadboy.revp.6767.domain=bazarr.isnadboy.com"
      - "docktail.service.enable=true"
      - "docktail.service.name=bazarr"
      - "docktail.service.port=6767"
      - "docktail.service.service-port=443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - bazarr-data:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/TV Shows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - default
      - sonarr_default
      - radarr_default

volumes:
  bazarr-data:
    external: true

networks:
  sonarr_default:
    external: true
  radarr_default:
    external: true
